name: Setup

description: Sets up the whole monorepo and install dependencies

inputs:
  VITE_KAKAO_JS_KEY:
    description: 'VITE Kakao JS Key'
    required: true

runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v5
      with:
        version: 10

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 24
        cache: 'pnpm'

    - name: Create .env file for Vite
      shell: bash
      run: |
        echo "VITE_KAKAO_JS_KEY=${{ inputs.VITE_KAKAO_JS_KEY }}" >> .env

    - name: Install dependencies
      shell: bash
      run: pnpm install
