name: Setup

description: Sets up the whole monorepo and install dependencies

runs:
  using: composite
  steps:
    - name: Setup Node.js and pnpm
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: pnpm
        cache-dependency-path: pnpm-lock.yaml

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9
        run_install: false

    - name: Create .env file for Vite
      run: |
        echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" >> .env
        echo "VITE_KAKAO_JS_KEY=${{ secrets.VITE_KAKAO_JS_KEY }}" >> .env

    - name: Install dependencies
      shell: bash
      run: pnpm install
