name: Setup

description: Sets up the whole monorepo and install dependencies

inputs:
  VITE_API_URL:
    description: 'VITE API URL'
    required: true
  VITE_KAKAO_JS_KEY:
    description: 'VITE Kakao JS Key'
    required: true

runs:
  using: composite
  steps:
    - name: Install dependencies
      uses: pnpm/action-setup@v4
      with:
        version: 9

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'pnpm'

    - name: Create .env file for Vite
      shell: bash
      run: |
        echo "VITE_API_URL=${{ inputs.VITE_API_URL }}" >> .env
        echo "VITE_KAKAO_JS_KEY=${{ inputs.VITE_KAKAO_JS_KEY }}" >> .env

    - name: Install dependencies
      shell: bash
      run: pnpm install
